### PR TITLE
Use Flags for passing params #6

### PR DESCRIPTION
**Pull request by leonardogcsoares**
Made the code shorter and requires less error handling. Not sure if the flags.go and flagset struct is the best option for readability/extensability, totally open to suggestions!

### CODE REVIEW

**Comment by blainsmith** [comment]
This is great! This will also set me up nicely for doing #2 and #3. 🤘 

Did you want to add #9 updates to this PR and knock out 2 issues with this one PR? I won't get a chance to pull it until later tonight anyway.

**Comment by leonardogcsoares** [comment]
Sure no worries!

**Comment by leonardogcsoares** [comment]
#9 done, slight lapse of laziness on my part haha

**Comment by blainsmith** [comment]
Thanks @leonardogcsoares! Made some minor tweaks before merging, but awesome job.

**Pull request merged**
